logging:
  level: INFO
  loggers:
    de.hof.university.smarthome.configurator: DEBUG
server:
  applicationConnectors:
  - type: http 
    port: 9000
  adminConnectors:
  - type: http
    port: 9001
database:
  driverClass: org.sqlite.JDBC
  url: jdbc:sqlite:/home/mrjustreborn/Dev/Yvi/mydb.sdb
  properties:
    charSet: UTF-8
    hibernate.dialect: com.enigmabridge.hibernate.dialect.SQLiteDialect
    hibernate.show_sql: false
    hibernate.generate_statistics: false
    hibernate.use_sql_comments: false